### ISSUE TITLE
형태소 분석기 오픈소스 성능 좋은 것 찾기

### ISSUE THREAD

**Issue by ejeongkim** [junsooo/Fake_love#11]
여러 형태소 분석기 중 사용이 간편하고 성능이 좋은 오픈 소스는 
twitter에서 제공하는 node-twitter-korean-text가 있다. 
하지만 이것은 간단한 문장 구조 '~하지 않다'를 잘 인식하지 못하는 문제가 있었다.

그리고 구글에서 제공하는 google analysis 는 성능과 더불어 형태소의 감정 분석까지 해줘서 감정 분석기를 
따로 쓸 필요가 없어서 좋았다. 

다른 더 좋은 형태소 와 감정 분석기가 있는 지 검색을 해 본다.

**Comment by deeptensorflow** [comment]
현재 파이썬의 버전으로는 트위터가 최선인 것으로 파악됨!
